remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
title: [CS-499 ePortfolio - Anthony Schissler]
description: [A culmination of efforts to efficiently improve past projects]
